playCheck = false
velocities = {}

function init(self)
	msg.post(".", "acquire_input_focus")
	timer.delay(0.01,true,function()
		for i,v in pairs(velocities) do 
			if playCheck then
				go.set_position(go.get_position(i)+v,i)
			end
		end
	end)
end

function on_input(self,action_id,action)
    if action_id == hash("space") then
        -- particlefx.set_constant("#trail", "emitter", "tint", vmath.vector4())
        playCheck = true
    end
end